version: '3.8'

services:
  postgres_bizease_develop:
    container_name: bizease-develop
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bizease-develop

  postgres_bizease_test:
    container_name: bizease-test
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bizease-test

  postgres_bizease:
    container_name: bizease
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bizease