ALTER TABLE users
    RENAME COLUMN roles TO role;

ALTER TABLE users
    ALTER COLUMN role TYPE VARCHAR(50);

ALTER TABLE users
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN password SET NOT NULL,
    ALTER COLUMN role SET NOT NULL;