ALTER TABLE users
ALTER COLUMN name SET NOT NULL,
ALTER COLUMN email SET NOT NULL,
ALTER COLUMN password SET NOT NULL,
ADD CONSTRAINT unique_email UNIQUE (email),
ADD COLUMN com_id BIGINT,
ADD CONSTRAINT fk_com_id FOREIGN KEY (com_id) REFERENCES commerces(id) ON DELETE CASCADE;



